services:
  irav-server:
    build: .
    ports:
      - "8080:80"
      - "8081:81"
      - "8082:82"
      - "2020:20"
      - "2021:21"
      - "40000-40100:40000-40100"
    volumes:
      - ./sites:/var/www/sites
       